### ISSUE TITLE
French text that needs to be translated to English

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Site-Web#3]
It's on [this](http://summerfields.info/?) page. And it says (Mise à jour de Minetest en version 0.4.14)

**Comment by lipki** [comment]
done!

**Comment by tobyplowy** [comment]
@lipki sorry can I be a little bit annoying. It's still wrong change it to (support for Minetest version 0.4.14) instead of (Minetest support Update to version 0.4.14)

**Comment by lipki** [comment]
il you want

**Comment by tobyplowy** [comment]
@lipki sorry I don't understand (il you want) did you try to say (if you want)?
